export type Rarity = "common" | "uncommon" | "rare" | "epic" | "legendary" | "???";

export interface ColorEntry {
  name: string;
  hex: string;
  rarity: Rarity;
}

export const RARITY_CONFIG: Record<Rarity, { emoji: string; weight: number; label: string; color: number }> = {
  common:    { emoji: "⚪", weight: 50,   label: "Common",    color: 0xaaaaaa },
  uncommon:  { emoji: "🟢", weight: 25,   label: "Uncommon",  color: 0x57f287 },
  rare:      { emoji: "🔵", weight: 14,   label: "Rare",      color: 0x3498db },
  epic:      { emoji: "🟣", weight: 8,    label: "Epic",      color: 0x9b59b6 },
  legendary: { emoji: "🟡", weight: 2.5,  label: "Legendary", color: 0xf1c40f },
  "???":     { emoji: "🌈", weight: 0.5,  label: "???",       color: 0xff6ec7 },
};

export const COLORS: ColorEntry[] = [
  // ── COMMON ──────────────────────────────────────────────────────────────────
  // Discord dark theme invisibles / near-blacks
  { name: "Discord Background",    hex: "#313338", rarity: "common" },
  { name: "Discord Sidebar",       hex: "#2b2d31", rarity: "common" },
  { name: "Discord Input",         hex: "#383a40", rarity: "common" },
  { name: "Discord Hover",         hex: "#35373c", rarity: "common" },
  { name: "Invisible Black",       hex: "#000001", rarity: "common" },
  { name: "Charcoal",              hex: "#36393f", rarity: "common" },
  { name: "Midnight",              hex: "#1a1a2e", rarity: "common" },
  { name: "Ash Gray",              hex: "#b2b2b2", rarity: "common" },
  { name: "Silver",                hex: "#c0c0c0", rarity: "common" },
  { name: "Light Gray",            hex: "#d3d3d3", rarity: "common" },
  { name: "White",                 hex: "#ffffff", rarity: "common" },
  { name: "Off White",             hex: "#f5f5f5", rarity: "common" },
  { name: "Ivory",                 hex: "#fffff0", rarity: "common" },
  { name: "Cream",                 hex: "#fffdd0", rarity: "common" },
  { name: "Snow",                  hex: "#fffafa", rarity: "common" },
  { name: "Beige",                 hex: "#f5f5dc", rarity: "common" },
  { name: "Linen",                 hex: "#faf0e6", rarity: "common" },
  { name: "Pale Gray",             hex: "#e8e8e8", rarity: "common" },
  { name: "Stone",                 hex: "#9e9e9e", rarity: "common" },
  { name: "Slate Gray",            hex: "#708090", rarity: "common" },
  { name: "Dim Gray",              hex: "#696969", rarity: "common" },
  { name: "Dark Gray",             hex: "#a9a9a9", rarity: "common" },
  { name: "Gainsboro",             hex: "#dcdcdc", rarity: "common" },
  { name: "Whitesmoke",            hex: "#f5f5f5", rarity: "common" },
  { name: "Light Steel Blue",      hex: "#b0c4de", rarity: "common" },
  { name: "Powder Blue",           hex: "#b0e0e6", rarity: "common" },
  { name: "Alice Blue",            hex: "#f0f8ff", rarity: "common" },
  { name: "Ghost White",           hex: "#f8f8ff", rarity: "common" },
  { name: "Azure",                 hex: "#f0ffff", rarity: "common" },
  { name: "Mint Cream",            hex: "#f5fffa", rarity: "common" },
  { name: "Honeydew",              hex: "#f0fff0", rarity: "common" },
  { name: "Lavender Blush",        hex: "#fff0f5", rarity: "common" },
  { name: "Misty Rose",            hex: "#ffe4e1", rarity: "common" },
  { name: "Seashell",              hex: "#fff5ee", rarity: "common" },
  { name: "Floral White",          hex: "#fffaf0", rarity: "common" },
  { name: "Old Lace",              hex: "#fdf5e6", rarity: "common" },
  { name: "Antique White",         hex: "#faebd7", rarity: "common" },
  { name: "Bisque",                hex: "#ffe4c4", rarity: "common" },
  { name: "Blanched Almond",       hex: "#ffebcd", rarity: "common" },
  { name: "Moccasin",              hex: "#ffe4b5", rarity: "common" },
  { name: "Navajo White",          hex: "#ffdead", rarity: "common" },
  { name: "Wheat",                 hex: "#f5deb3", rarity: "common" },
  { name: "Burlywood",             hex: "#deb887", rarity: "common" },
  { name: "Tan",                   hex: "#d2b48c", rarity: "common" },
  { name: "Sandy Brown",           hex: "#f4a460", rarity: "common" },
  { name: "Rosewood",              hex: "#65000b", rarity: "common" },
  { name: "Maroon",                hex: "#800000", rarity: "common" },
  { name: "Dark Red",              hex: "#8b0000", rarity: "common" },
  { name: "Brown",                 hex: "#a52a2a", rarity: "common" },
  { name: "Saddle Brown",          hex: "#8b4513", rarity: "common" },
  { name: "Sienna",                hex: "#a0522d", rarity: "common" },
  { name: "Peru",                  hex: "#cd853f", rarity: "common" },
  { name: "Chocolate",             hex: "#d2691e", rarity: "common" },
  { name: "Dark Salmon",           hex: "#e9967a", rarity: "common" },
  { name: "Rosy Brown",            hex: "#bc8f8f", rarity: "common" },
  { name: "Indian Red",            hex: "#cd5c5c", rarity: "common" },
  { name: "Light Coral",           hex: "#f08080", rarity: "common" },
  { name: "Salmon",                hex: "#fa8072", rarity: "common" },
  { name: "Tomato",                hex: "#ff6347", rarity: "common" },
  { name: "Coral",                 hex: "#ff7f50", rarity: "common" },
  { name: "Orange Red",            hex: "#ff4500", rarity: "common" },
  { name: "Dark Orange",           hex: "#ff8c00", rarity: "common" },
  { name: "Orange",                hex: "#ffa500", rarity: "common" },
  { name: "Gold",                  hex: "#ffd700", rarity: "common" },
  { name: "Yellow",                hex: "#ffff00", rarity: "common" },
  { name: "Light Yellow",          hex: "#ffffe0", rarity: "common" },
  { name: "Lemon Chiffon",         hex: "#fffacd", rarity: "common" },
  { name: "Light Goldenrod",       hex: "#fafad2", rarity: "common" },
  { name: "Papaya Whip",           hex: "#ffefd5", rarity: "common" },
  { name: "Peach Puff",            hex: "#ffdab9", rarity: "common" },
  { name: "Khaki",                 hex: "#f0e68c", rarity: "common" },
  { name: "Dark Khaki",            hex: "#bdb76b", rarity: "common" },
  { name: "Yellow Green",          hex: "#9acd32", rarity: "common" },
  { name: "Olive Drab",            hex: "#6b8e23", rarity: "common" },
  { name: "Olive",                 hex: "#808000", rarity: "common" },
  { name: "Dark Olive Green",      hex: "#556b2f", rarity: "common" },
  { name: "Lawn Green",            hex: "#7cfc00", rarity: "common" },
  { name: "Chartreuse",            hex: "#7fff00", rarity: "common" },
  { name: "Green Yellow",          hex: "#adff2f", rarity: "common" },
  { name: "Lime Green",            hex: "#32cd32", rarity: "common" },
  { name: "Pale Green",            hex: "#98fb98", rarity: "common" },
  { name: "Light Green",           hex: "#90ee90", rarity: "common" },
  { name: "Medium Sea Green",      hex: "#3cb371", rarity: "common" },
  { name: "Sea Green",             hex: "#2e8b57", rarity: "common" },
  { name: "Forest Green",          hex: "#228b22", rarity: "common" },
  { name: "Green",                 hex: "#008000", rarity: "common" },
  { name: "Dark Green",            hex: "#006400", rarity: "common" },
  { name: "Teal",                  hex: "#008080", rarity: "common" },
  { name: "Dark Teal",             hex: "#004040", rarity: "common" },
  { name: "Dark Cyan",             hex: "#008b8b", rarity: "common" },
  { name: "Cyan",                  hex: "#00ffff", rarity: "common" },
  { name: "Aquamarine",            hex: "#7fffd4", rarity: "common" },
  { name: "Medium Aquamarine",     hex: "#66cdaa", rarity: "common" },
  { name: "Cadet Blue",            hex: "#5f9ea0", rarity: "common" },
  { name: "Steel Blue",            hex: "#4682b4", rarity: "common" },
  { name: "Light Blue",            hex: "#add8e6", rarity: "common" },
  { name: "Sky Blue",              hex: "#87ceeb", rarity: "common" },
  { name: "Deep Sky Blue",         hex: "#00bfff", rarity: "common" },
  { name: "Dodger Blue",           hex: "#1e90ff", rarity: "common" },
  { name: "Cornflower Blue",       hex: "#6495ed", rarity: "common" },
  { name: "Medium Blue",           hex: "#0000cd", rarity: "common" },
  { name: "Blue",                  hex: "#0000ff", rarity: "common" },
  { name: "Dark Blue",             hex: "#00008b", rarity: "common" },
  { name: "Navy",                  hex: "#000080", rarity: "common" },
  { name: "Midnight Blue",         hex: "#191970", rarity: "common" },
  { name: "Lavender",              hex: "#e6e6fa", rarity: "common" },
  { name: "Thistle",               hex: "#d8bfd8", rarity: "common" },
  { name: "Plum",                  hex: "#dda0dd", rarity: "common" },
  { name: "Violet",                hex: "#ee82ee", rarity: "common" },
  { name: "Orchid",                hex: "#da70d6", rarity: "common" },
  { name: "Fuchsia",               hex: "#ff00ff", rarity: "common" },
  { name: "Magenta",               hex: "#ff00ff", rarity: "common" },
  { name: "Medium Orchid",         hex: "#ba55d3", rarity: "common" },
  { name: "Dark Orchid",           hex: "#9932cc", rarity: "common" },
  { name: "Dark Violet",           hex: "#9400d3", rarity: "common" },
  { name: "Blue Violet",           hex: "#8a2be2", rarity: "common" },
  { name: "Dark Magenta",          hex: "#8b008b", rarity: "common" },
  { name: "Purple",                hex: "#800080", rarity: "common" },
  { name: "Indigo",                hex: "#4b0082", rarity: "common" },
  { name: "Hot Pink",              hex: "#ff69b4", rarity: "common" },
  { name: "Deep Pink",             hex: "#ff1493", rarity: "common" },
  { name: "Pink",                  hex: "#ffc0cb", rarity: "common" },
  { name: "Light Pink",            hex: "#ffb6c1", rarity: "common" },
  { name: "Pale Violet Red",       hex: "#db7093", rarity: "common" },
  { name: "Medium Violet Red",     hex: "#c71585", rarity: "common" },
  { name: "Crimson",               hex: "#dc143c", rarity: "common" },
  { name: "Red",                   hex: "#ff0000", rarity: "common" },
  { name: "Fire Brick",            hex: "#b22222", rarity: "common" },

  // ── UNCOMMON ─────────────────────────────────────────────────────────────────
  { name: "Neon Green",            hex: "#39ff14", rarity: "uncommon" },
  { name: "Electric Blue",         hex: "#7df9ff", rarity: "uncommon" },
  { name: "Hot Coral",             hex: "#ff6b6b", rarity: "uncommon" },
  { name: "Pastel Purple",         hex: "#b39ddb", rarity: "uncommon" },
  { name: "Soft Mint",             hex: "#aaf0d1", rarity: "uncommon" },
  { name: "Butter Yellow",         hex: "#fffd82", rarity: "uncommon" },
  { name: "Dusty Rose",            hex: "#dcae96", rarity: "uncommon" },
  { name: "Tiffany Blue",          hex: "#81d8d0", rarity: "uncommon" },
  { name: "Periwinkle",            hex: "#ccccff", rarity: "uncommon" },
  { name: "Mauve",                 hex: "#e0b0ff", rarity: "uncommon" },
  { name: "Champagne",             hex: "#f7e7ce", rarity: "uncommon" },
  { name: "Slate Blue",            hex: "#6a5acd", rarity: "uncommon" },
  { name: "Medium Slate Blue",     hex: "#7b68ee", rarity: "uncommon" },
  { name: "Turquoise",             hex: "#40e0d0", rarity: "uncommon" },
  { name: "Medium Turquoise",      hex: "#48d1cc", rarity: "uncommon" },
  { name: "Dark Turquoise",        hex: "#00ced1", rarity: "uncommon" },
  { name: "Spring Green",          hex: "#00ff7f", rarity: "uncommon" },
  { name: "Medium Spring Green",   hex: "#00fa9a", rarity: "uncommon" },
  { name: "Pale Turquoise",        hex: "#afeeee", rarity: "uncommon" },
  { name: "Light Sea Green",       hex: "#20b2aa", rarity: "uncommon" },
  { name: "Medium Purple",         hex: "#9370db", rarity: "uncommon" },
  { name: "Rebecca Purple",        hex: "#663399", rarity: "uncommon" },
  { name: "Slate",                 hex: "#6d8a8a", rarity: "uncommon" },
  { name: "Sage",                  hex: "#b2ac88", rarity: "uncommon" },
  { name: "Caramel",               hex: "#c68642", rarity: "uncommon" },
  { name: "Rust",                  hex: "#b7410e", rarity: "uncommon" },
  { name: "Terra Cotta",           hex: "#e2725b", rarity: "uncommon" },
  { name: "Burnt Orange",          hex: "#cc5500", rarity: "uncommon" },
  { name: "Amber",                 hex: "#ffbf00", rarity: "uncommon" },
  { name: "Goldenrod",             hex: "#daa520", rarity: "uncommon" },
  { name: "Dark Goldenrod",        hex: "#b8860b", rarity: "uncommon" },
  { name: "Pale Goldenrod",        hex: "#eee8aa", rarity: "uncommon" },
  { name: "Mint Green",            hex: "#98ff98", rarity: "uncommon" },
  { name: "Jade",                  hex: "#00a86b", rarity: "uncommon" },
  { name: "Emerald",               hex: "#50c878", rarity: "uncommon" },
  { name: "Cobalt Blue",           hex: "#0047ab", rarity: "uncommon" },
  { name: "Royal Blue",            hex: "#4169e1", rarity: "uncommon" },
  { name: "Sapphire",              hex: "#0f52ba", rarity: "uncommon" },
  { name: "Powder Pink",           hex: "#ffb3ba", rarity: "uncommon" },
  { name: "Blush",                 hex: "#de5d83", rarity: "uncommon" },
  { name: "Rose",                  hex: "#ff007f", rarity: "uncommon" },
  { name: "Cerise",                hex: "#de3163", rarity: "uncommon" },
  { name: "Raspberry",             hex: "#e30b5d", rarity: "uncommon" },
  { name: "Mulberry",              hex: "#c54b8c", rarity: "uncommon" },
  { name: "Eggplant",              hex: "#614051", rarity: "uncommon" },
  { name: "Wine",                  hex: "#722f37", rarity: "uncommon" },
  { name: "Burgundy",              hex: "#800020", rarity: "uncommon" },
  { name: "Vermilion",             hex: "#e34234", rarity: "uncommon" },
  { name: "Scarlet",               hex: "#ff2400", rarity: "uncommon" },
  { name: "Sunset Orange",         hex: "#fd5e53", rarity: "uncommon" },
  { name: "Peach",                 hex: "#ffcba4", rarity: "uncommon" },
  { name: "Apricot",               hex: "#fbceb1", rarity: "uncommon" },
  { name: "Tangerine",             hex: "#f28500", rarity: "uncommon" },
  { name: "Paprika",               hex: "#8d1c02", rarity: "uncommon" },
  { name: "Cinnamon",              hex: "#d2691e", rarity: "uncommon" },
  { name: "Mocha",                 hex: "#967117", rarity: "uncommon" },
  { name: "Cappuccino",            hex: "#4a2c2a", rarity: "uncommon" },
  { name: "Espresso",              hex: "#2c1503", rarity: "uncommon" },
  { name: "Walnut",                hex: "#5c3d11", rarity: "uncommon" },
  { name: "Mahogany",              hex: "#c04000", rarity: "uncommon" },
  { name: "Taupe",                 hex: "#483c32", rarity: "uncommon" },
  { name: "Ecru",                  hex: "#c2b280", rarity: "uncommon" },
  { name: "Parchment",             hex: "#f1e9d2", rarity: "uncommon" },
  { name: "Vanilla",               hex: "#f3e5ab", rarity: "uncommon" },
  { name: "Lemon",                 hex: "#fff44f", rarity: "uncommon" },
  { name: "Lime",                  hex: "#00ff00", rarity: "uncommon" },
  { name: "Avocado",               hex: "#568203", rarity: "uncommon" },
  { name: "Fern",                  hex: "#4f7942", rarity: "uncommon" },
  { name: "Moss",                  hex: "#8a9a5b", rarity: "uncommon" },
  { name: "Seafoam",               hex: "#71eeb8", rarity: "uncommon" },
  { name: "Ice Blue",              hex: "#d6f0f5", rarity: "uncommon" },
  { name: "Baby Blue",             hex: "#89cff0", rarity: "uncommon" },
  { name: "Denim",                 hex: "#1560bd", rarity: "uncommon" },
  { name: "Iris",                  hex: "#5a4fcf", rarity: "uncommon" },
  { name: "Wisteria",              hex: "#c9a0dc", rarity: "uncommon" },
  { name: "Lilac",                 hex: "#c8a2c8", rarity: "uncommon" },
  { name: "Lavender Purple",       hex: "#967bb6", rarity: "uncommon" },
  { name: "Heliotrope",            hex: "#df73ff", rarity: "uncommon" },

  // ── RARE ─────────────────────────────────────────────────────────────────────
  { name: "Lapis Lazuli",          hex: "#26619c", rarity: "rare" },
  { name: "Persian Blue",          hex: "#1c39bb", rarity: "rare" },
  { name: "Byzantine",             hex: "#bd33a4", rarity: "rare" },
  { name: "Amaranth",              hex: "#e52b50", rarity: "rare" },
  { name: "Amaranth Purple",       hex: "#ab274f", rarity: "rare" },
  { name: "Vivid Violet",          hex: "#9f00ff", rarity: "rare" },
  { name: "Neon Blue",             hex: "#1b03a3", rarity: "rare" },
  { name: "Neon Purple",           hex: "#bc13fe", rarity: "rare" },
  { name: "Neon Pink",             hex: "#ff6ec7", rarity: "rare" },
  { name: "Neon Yellow",           hex: "#dfff00", rarity: "rare" },
  { name: "Neon Orange",           hex: "#ff6700", rarity: "rare" },
  { name: "Neon Red",              hex: "#ff3131", rarity: "rare" },
  { name: "Neon Cyan",             hex: "#00ffff", rarity: "rare" },
  { name: "Electric Violet",       hex: "#8f00ff", rarity: "rare" },
  { name: "Electric Indigo",       hex: "#6f00ff", rarity: "rare" },
  { name: "Electric Crimson",      hex: "#ff003f", rarity: "rare" },
  { name: "Electric Green",        hex: "#00ff00", rarity: "rare" },
  { name: "Cerulean",              hex: "#007ba7", rarity: "rare" },
  { name: "Ultramarine",           hex: "#3f00ff", rarity: "rare" },
  { name: "Prussian Blue",         hex: "#003153", rarity: "rare" },
  { name: "Oxblood",               hex: "#4a0000", rarity: "rare" },
  { name: "Bordeaux",              hex: "#5c0120", rarity: "rare" },
  { name: "Deep Carmine",          hex: "#a9203e", rarity: "rare" },
  { name: "Carmine",               hex: "#960018", rarity: "rare" },
  { name: "Crimson Glory",         hex: "#be0032", rarity: "rare" },
  { name: "Malachite",             hex: "#0bda51", rarity: "rare" },
  { name: "Shamrock",              hex: "#009e60", rarity: "rare" },
  { name: "Viridian",              hex: "#40826d", rarity: "rare" },
  { name: "Forest Night",          hex: "#014421", rarity: "rare" },
  { name: "Hunter Green",          hex: "#355e3b", rarity: "rare" },
  { name: "Jungle Green",          hex: "#29ab87", rarity: "rare" },
  { name: "Phthalocyanine Blue",   hex: "#000f89", rarity: "rare" },
  { name: "Saffron",               hex: "#f4c430", rarity: "rare" },
  { name: "Turmeric",              hex: "#cda323", rarity: "rare" },
  { name: "Burnt Sienna",          hex: "#e97451", rarity: "rare" },
  { name: "Venetian Red",          hex: "#c80815", rarity: "rare" },
  { name: "Pompeian Red",          hex: "#c0392b", rarity: "rare" },
  { name: "Dragon Red",            hex: "#7d0000", rarity: "rare" },
  { name: "Onyx",                  hex: "#353935", rarity: "rare" },
  { name: "Jet Black",             hex: "#0a0a0a", rarity: "rare" },
  { name: "Obsidian",              hex: "#1b1b1b", rarity: "rare" },
  { name: "Raven",                 hex: "#0c0c0c", rarity: "rare" },
  { name: "Pitch Black",           hex: "#050505", rarity: "rare" },
  { name: "Gunmetal",              hex: "#2a3439", rarity: "rare" },
  { name: "Platinum",              hex: "#e5e4e2", rarity: "rare" },
  { name: "Moonstone",             hex: "#3aa8c1", rarity: "rare" },
  { name: "Aqua Vitae",            hex: "#00c5cd", rarity: "rare" },
  { name: "Peacock Blue",          hex: "#33a1c9", rarity: "rare" },
  { name: "Discord Blurple",       hex: "#5865f2", rarity: "rare" },
  { name: "Discord Green",         hex: "#57f287", rarity: "rare" },
  { name: "Discord Yellow",        hex: "#fee75c", rarity: "rare" },
  { name: "Discord Fuchsia",       hex: "#eb459e", rarity: "rare" },
  { name: "Discord Red",           hex: "#ed4245", rarity: "rare" },
  { name: "Discord White",         hex: "#ffffff", rarity: "rare" },

  // ── EPIC ─────────────────────────────────────────────────────────────────────
  { name: "Aurora Borealis",       hex: "#54dfc0", rarity: "epic" },
  { name: "Twilight",              hex: "#4f3a6e", rarity: "epic" },
  { name: "Nebula Pink",           hex: "#e040fb", rarity: "epic" },
  { name: "Cosmic Purple",         hex: "#7b2d8b", rarity: "epic" },
  { name: "Stardust",              hex: "#d4a0ff", rarity: "epic" },
  { name: "Galaxy Blue",           hex: "#13274f", rarity: "epic" },
  { name: "Solar Flare",           hex: "#ff6b00", rarity: "epic" },
  { name: "Supernova",             hex: "#ff3d00", rarity: "epic" },
  { name: "Void Black",            hex: "#020209", rarity: "epic" },
  { name: "Deep Space",            hex: "#0d0221", rarity: "epic" },
  { name: "Blood Moon",            hex: "#a80000", rarity: "epic" },
  { name: "Abyssal Blue",          hex: "#00005f", rarity: "epic" },
  { name: "Shadow Indigo",         hex: "#1f0040", rarity: "epic" },
  { name: "Midnight Teal",         hex: "#003333", rarity: "epic" },
  { name: "Phantom Green",         hex: "#003300", rarity: "epic" },
  { name: "Dark Matter",           hex: "#111111", rarity: "epic" },
  { name: "Glitch Pink",           hex: "#ff2079", rarity: "epic" },
  { name: "Plasma Blue",           hex: "#00b4d8", rarity: "epic" },
  { name: "Quantum Teal",          hex: "#009688", rarity: "epic" },
  { name: "Event Horizon",         hex: "#050505", rarity: "epic" },
  { name: "Pulsar",                hex: "#7400b8", rarity: "epic" },
  { name: "Quasar",                hex: "#6930c3", rarity: "epic" },
  { name: "Antimatter",            hex: "#48005a", rarity: "epic" },
  { name: "Wormhole",              hex: "#240046", rarity: "epic" },
  { name: "Dark Energy",           hex: "#10002b", rarity: "epic" },
  { name: "Photon Blue",           hex: "#0077b6", rarity: "epic" },
  { name: "Ion Storm",             hex: "#023e8a", rarity: "epic" },
  { name: "Spectral Violet",       hex: "#560bad", rarity: "epic" },
  { name: "Aether Purple",         hex: "#480ca8", rarity: "epic" },
  { name: "Dimensional Rift",      hex: "#3a0ca3", rarity: "epic" },
  { name: "Holographic",           hex: "#c0f0ff", rarity: "epic" },
  { name: "Cyberpunk Yellow",      hex: "#f0ff00", rarity: "epic" },
  { name: "Cyberpunk Pink",        hex: "#ff2d78", rarity: "epic" },
  { name: "Matrix Green",          hex: "#00ff41", rarity: "epic" },
  { name: "Neural Blue",           hex: "#0d47a1", rarity: "epic" },
  { name: "Synthwave Red",         hex: "#ff0a54", rarity: "epic" },
  { name: "Synthwave Purple",      hex: "#9d00ff", rarity: "epic" },
  { name: "Synthwave Teal",        hex: "#00d9ff", rarity: "epic" },
  { name: "Vaporwave Pink",        hex: "#ff71ce", rarity: "epic" },
  { name: "Vaporwave Blue",        hex: "#01cdfe", rarity: "epic" },
  { name: "Vaporwave Purple",      hex: "#b967ff", rarity: "epic" },
  { name: "Retrowave Orange",      hex: "#ff6d00", rarity: "epic" },

  // ── LEGENDARY ────────────────────────────────────────────────────────────────
  { name: "Bidoof Gold",           hex: "#f5c842", rarity: "legendary" },
  { name: "Shiny Gold",            hex: "#ffd700", rarity: "legendary" },
  { name: "True Gold",             hex: "#ffcc00", rarity: "legendary" },
  { name: "Ancient Gold",          hex: "#cfb53b", rarity: "legendary" },
  { name: "Midas Touch",           hex: "#e8c325", rarity: "legendary" },
  { name: "Dragon Scale",          hex: "#008000", rarity: "legendary" },
  { name: "Phoenix Fire",          hex: "#ff4500", rarity: "legendary" },
  { name: "Celestial Blue",        hex: "#4169e1", rarity: "legendary" },
  { name: "Divine White",          hex: "#fffef0", rarity: "legendary" },
  { name: "Infernal Red",          hex: "#ff0000", rarity: "legendary" },
  { name: "Arcane Purple",         hex: "#800080", rarity: "legendary" },
  { name: "Mythril Silver",        hex: "#aac8d4", rarity: "legendary" },
  { name: "Adamantite Blue",       hex: "#1b5e20", rarity: "legendary" },
  { name: "True Silver",           hex: "#c0c0c0", rarity: "legendary" },
  { name: "Eldritch Green",        hex: "#006400", rarity: "legendary" },
  { name: "Sacred Crimson",        hex: "#c41e3a", rarity: "legendary" },
  { name: "Eternal Night",         hex: "#000033", rarity: "legendary" },
  { name: "Cosmos Black",          hex: "#000011", rarity: "legendary" },
  { name: "Primordial Void",       hex: "#000000", rarity: "legendary" },
  { name: "True Pure White",       hex: "#fefefe", rarity: "legendary" },
  { name: "Angel White",           hex: "#f8f8ff", rarity: "legendary" },
  { name: "Demon Black",           hex: "#010101", rarity: "legendary" },
  { name: "Lich Purple",           hex: "#4b0082", rarity: "legendary" },
  { name: "Wyvern Teal",           hex: "#008080", rarity: "legendary" },
  { name: "Vampire Crimson",       hex: "#8b0000", rarity: "legendary" },
  { name: "Werewolf Brown",        hex: "#964b00", rarity: "legendary" },
  { name: "Opal",                  hex: "#a8c3bc", rarity: "legendary" },
  { name: "Ruby",                  hex: "#9b111e", rarity: "legendary" },
  { name: "Sapphire Blue",         hex: "#0f52ba", rarity: "legendary" },
  { name: "Emerald Green",         hex: "#50c878", rarity: "legendary" },
  { name: "Amethyst",              hex: "#9966cc", rarity: "legendary" },
  { name: "Diamond",               hex: "#b9f2ff", rarity: "legendary" },

  // ── ??? ──────────────────────────────────────────────────────────────────────
  { name: "Bidoof's Blessing",     hex: "#f7dc6f", rarity: "???" },
  { name: "Ditto Purple",          hex: "#b57adf", rarity: "???" },
  { name: "Missingno",             hex: "#ff00ff", rarity: "???" },
  { name: "Shiny Bidoof",          hex: "#dcc48a", rarity: "???" },
  { name: "True Invisible",        hex: "#2b2d31", rarity: "???" },
  { name: "Void",                  hex: "#000000", rarity: "???" },
  { name: "Error Color",           hex: "#ff0000", rarity: "???" },
  { name: "Glitched",              hex: "#00ff00", rarity: "???" },
  { name: "404 Blue",              hex: "#0000ff", rarity: "???" },
  { name: "Time Paradox",          hex: "#ffffff", rarity: "???" },
  { name: "Reality Break",         hex: "#ff00ff", rarity: "???" },
  { name: "Dimensional Bleed",     hex: "#00ffff", rarity: "???" },
  { name: "Null",                  hex: "#010101", rarity: "???" },
  { name: "Undefined",             hex: "#fefefe", rarity: "???" },
  { name: "Overflow",              hex: "#ff8800", rarity: "???" },
  { name: "The One Color",         hex: "#5865f2", rarity: "???" },
  { name: "Bidoof's True Form",    hex: "#a0522d", rarity: "???" },
  { name: "Mod Color",             hex: "#ed4245", rarity: "???" },
];

export function rollRarity(guaranteed?: "epic" | "legendary"): Rarity {
  if (guaranteed === "epic") {
    const epicPlus: Rarity[] = ["epic", "legendary", "???"];
    const weights = [70, 25, 5];
    return weightedRandom(epicPlus, weights);
  }
  if (guaranteed === "legendary") {
    const legPlus: Rarity[] = ["legendary", "???"];
    const weights = [90, 10];
    return weightedRandom(legPlus, weights);
  }

  const rarities = Object.keys(RARITY_CONFIG) as Rarity[];
  const weights = rarities.map((r) => RARITY_CONFIG[r].weight);
  return weightedRandom(rarities, weights);
}

function weightedRandom<T>(items: T[], weights: number[]): T {
  const total = weights.reduce((a, b) => a + b, 0);
  let r = Math.random() * total;
  for (let i = 0; i < items.length; i++) {
    r -= weights[i]!;
    if (r <= 0) return items[i]!;
  }
  return items[items.length - 1]!;
}

export function randomColorByRarity(rarity: Rarity): ColorEntry {
  const pool = COLORS.filter((c) => c.rarity === rarity);
  return pool[Math.floor(Math.random() * pool.length)]!;
}
